name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - run: echo 'github action'
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          script: |
            PATH=$PATH:/home/${{secrets.REMOTE_USER}}/.nvm/versions/node/v18.16.0/bin 
            nvm use 18.16.0
            cd /home/ubuntu/pixel-art
            git pull origin main
            cd backend
            npm i --force
            npm run build
            cd ..
            cd frontend
            npm i --force
            npm run build
            cd ..
            pm2 reload all
