name: build backend application

on:
  push:
    branches: [main]
    paths: 
      - backend/src/*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/pixel-art
            git pull origin main
            cd backend
            npm i --force
            npm run build
            cd ..
            pm2 reload all
